server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: qi-api-interface
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
  redis:
    port: 6379
    host: 192.168.42.132
    database: 0
    password: 230410
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848